# [TIL] - 리액트 입문 강의, JS의 비동기 작업 강의, 리액트 챌린지반 세션

## ✅ 공부한 내용

### ✔️ [리액트 정기세션 1회](https://github.com/minyoungKuk/challenge-class/blob/main/assignments/01/0513%EA%B3%BC%EC%A0%9C.md)

### ✔️ [딥다이브 스터디](https://github.com/hyeonseok98/js-deep-dive-study/blob/main/%5B09%EC%9E%A5%5D%20%ED%83%80%EC%9E%85%20%EB%B3%80%ED%99%98%EA%B3%BC%20%EB%8B%A8%EC%B6%95%20%ED%8F%89%EA%B0%80/%EA%B5%AD%EB%AF%BC%EC%98%81.md)

### ​✔️ JS의 비동기 작업 강의

#### 동기적 작업 흐름과 비동기적 작업 흐름

- 동기적 처리 : 선행 작업이 끝날 때까지 기다렸다가 후행 작업이 진행되는 작업 흐름

```jsx
// 동기적 작업 흐름의 예
console.log(1);
console.log(2);
console.log(3);

// 1 2 3
```

- 비동기 처리 : 동기적 작업 흐름을 따르지 않는 흐름

```jsx
// 비동기 처리의 예
console.log(1);
setTimeout(() => {
  console.log(2);
}, 1000);
console.log(3);

// 1 3 2
```

#### Promise : "비동기적으로 작업을 처리해주겠다"라는 약속^^❤️‍🔥

1. Promise의 3가지 상태

- pending ➡️ 약속을 막 한 상태 (약속 생성)
- fulfilled ➡️ 약속을 성공적으로 잘 수행한 상태 (약속 지킴)
- rejected ➡️ 약속을 성족적으로 수행하지 못한 생태 (약속 못지킴)

2. 약속 만드는 방법

- new Promise()

```jsx
// 1부터 n까지의 합을 구하는 예제
function calculateSum(n) {
  return new Promise((resolve, reject) => {
    if (typeof n !== number || n <= 0) {
      reject(new Error("잘못된 입력입니다"));
    }
    let sum = 0;
    for (let i = 1; i <= n; i++) {
      sum += i;
    }
    resolve(sum); // 계산이 완료되면 결과를 resolve
  });
}

async function main() {
  try {
    let result = await calculateSum(5);
    console.log("성공", result);
  } catch (error) {
    console.log("실패", error.message);
  }
}

main();
```

- async function () {} : async함수는 항상 promise를 리턴

```jsx
// 1부터 n까지의 합을 구하는 예제
async function calculate(n) {
  if (typeof n !== n || n <= 0) {
    throw new Error('잘못된 입력입니다')
  }
  let sum = 0;
  fot (let i = 0; i <= n; i++) {
    sum += i
  }
  return sum
}

async function main () {
  try {
    let result = await calculateSum(5)
    console.log('성공', result)
  } catch (error) {
    console.log('실패', error.message)
  }
}

main()

```

- 약속을 then으로 이어나갈 경우

```jsx
// 1부터 n까지의 합을 구한 후, 결과를 제곱하는 예제
async function calculateSumAndSquare(n) {
  try {
    let sum = await calcilateSum(n);
    return sum * sum;
  } catch {
    throw error;
  }
}

calculateSumAndSquare(5)
  .then((result) => {
    console.log(result);
  })
  .catch((error) => {
    console.log("실패", error.message);
  });
```
